spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=cicp_admin
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      # 连接池最大连接数
      maximum-pool-size: 20
      # 连接池最小空闲连接数
      minimum-idle: 8
      # 连接超时时间（毫秒）
      connection-timeout: 30000
      # 连接最大存活时间（毫秒,即 30 分钟）
      max-lifetime: 1800000
      # 连接空闲超时时间（毫秒，即 10 分钟）
      idle-timeout: 600000
      # 连接测试查询
      connection-test-query: select 1
      # 验证超时（毫秒）
      validation-timeout: 5000
      # 泄露检测
      leak-detection-threshold: 60000
      # 禁止暂停连接池
      allow-pool-suspension: false
      # 自动提交事务
      auto-commit: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      #password:
      database: 15
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

# springdoc-openapi项目配置
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  packages-to-scan: com.lwd.admin
  group-configs:
    - group: 'default'
      paths-to-match:
        - '/user/**'
# knife4j的增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体列表
